<div class="row m-3">
    <div class="col-lg-12">
        <form method="post" action="<?= $_SERVER['PHP_SELF'] ?>">
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label for="client">Client</label>
                    <select id="client" name="client" class="form-control">
                        <option selected>Choose...</option>
                        <?php foreach ($users as $user) { ?>
                            <option value="<?= $user->id ?>"><?= $user->name ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="form-group col-md-4">
                    <label for="account">Account</label>
                    <select id="account" name="account" class="form-control">
                        <option selected>Choose...</option>
                    </select>
                </div>
                <div class="form-group col-md-2">
                    <label for="amount">Amount</label>
                    <input type="number" class="form-control" name="amount" id="amount">
                </div>
                <div class="form-group col-md-2">
                    <button type="submit" class="btn btn-primary" style="margin-top: 39px;">Send</button>
                </div>
            </div>
        </form>
        <p><?php $this->flashSession->output() ?></p>
    </div>
</div>

<script>
    $(document).ready(function () {
        jQuery('#client').change(function () {
            var id = jQuery("select option:selected").val();
            $.get("ajax/accounts/" + id, function (data) {
                if (data) {
                    jQuery('#account').empty().append('<option>Choose...</option>');
                    jQuery.each(data, function (i, row) {
                        jQuery('#account').append(
                            jQuery('<option></option>').val(row.id).html('Account - ' + row.currency + ': ' + row.id)
                        );
                    });
                }
            });
        });
    });
</script>