<div class="row m-3">
    <div class="col-lg-12">
        <form class="form-inline">
            <span>Calculate Rates: </span>
            <button type="submit" class="btn btn-primary">Start</button>
        </form>
    </div>
</div>
<div class="row m-4">
    <div class="col-lg-12">
    <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">25%</div>
    </div>
    </div>
</div>